name: Daily Update Challenges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1,3,5' # scheduled to run at 6:00 AM on Mondays, Wednesdays, and Fridays.
    - cron: '0 6 * * 2,4,6' # scheduled to run at 6:00 AM on Tuesdays, Thursdays, and Saturdays.
    - cron: '0 6 25,28 * *' # scheduled to run at 6:00 AM on the 25th and 28th day of every month.


permissions:
  contents: write

jobs:
  update-challenges:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: qlefevre/strava-challenges-global
        path: source-repo
        ref: main

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: qlefevre/strava-challenges-global
        path: target-repo
        ref: main

    - name: Prepare update-challenges.js
      run: |
        cd source-repo
        npm install axios fs-extra

    - name: Update challenges.json 2 15
      if: github.event.schedule == '0 6 * * 1,3,5'
      run: node ./update/update-challenge.js challenges.json ../target-repo/challenges.json 5 15

    - name: Update challenges.json 1 30
      if: github.event.schedule == '0 6 25,28 * *'
      run: node ./update/update-challenge.js challenges.json ../target-repo/challenges.json 1 30

    - name: Update challenges.json 8 5
      if: github.event.schedule != '0 6 25,28 * *' && github.event.schedule == '0 6 * * 1,3,5'
      run: node ./update/update-challenge.js challenges.json ../target-repo/challenges.json 8 5

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        cd target-repo
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update Challenge"
          git push origin main
        fi
